[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"] # You can also use cdylib, depending on your project

[dependencies]
ocaml-sys = "0.23"
wasmparser = "0.93" 

[build-dependencies]
cc = "1"

