name: Publish tagged release image

on:
  push:
    tags:
      - 'v*.*.*'

env: 
  VERSION: ${{ github.ref_name }} 

jobs:
  push_to_ghcr:
    name: Push to GitHub container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # push to github container registry
      - name: Log in to github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build, tag, & push the latest image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/dylibso/wasmstore:${VERSION#v}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # push to dockerhub
      - name: Log in to dockerhub registry
        uses: docker/login-action@v2
        with:
          username: dylibso
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, & push the latest image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: dylibso/wasmstore:${VERSION#v}
          cache-from: type=gha
          cache-to: type=gha,mode=max
